### ISSUE TITLE
convertBreakdancerBedToBedpe output malformed bedpe file

### ISSUE THREAD

**Issue by ponizvezdochka** [cwhelan/sv-annotate#1]
Hello!
Currently trying to use your script convertBreakdancerBedToBedpe with breakdancer file, but output bedpe file contains many rows where start1>end1. Script annotate_bedpe.py fails with error:
pybedtools.cbedtools.MalformedBedLineError: Start is greater than stop. What's was the logic of converting bedpe file from bed? How we choose start and stop from multiple reads which support one breakpoint?

Thank you!

**Comment by cwhelan** [comment]
Hi,

It's been a while since I looked at or used this, but the logic should be
that the start1 and end1 are set as the min starting position of the reads
supporting the left breakpoint region, and the max ending position. So if
the read pairs supporting a deletion were like this:

pair1:
read1: 1 1000 1100
read2:  1 2000 2100

pair2:
read1: 1 1010 1110
read2: 1 2020 2120

the bedpe record should say:

1 1000 1110  1 2000 2120

What does the bed file you are feeding into the script look like?

Chris

**Comment by ponizvezdochka** [comment]
Hi Chris!

I suspect that something wrong with breakdancer bed file, because all reads have start > end there:

```
track name=chr1_901835_DEL_260  description="BreakDancer chr1 901835 DEL 260"   useScore=0
chr1    902045  901961  MG00HS05:416:C35D4ACXX:1:1305:3595:49116|fz7445-lib     600     1       902045  901961  255,0,0
chr1    901738  901636  MG00HS05:416:C35D4ACXX:1:1305:3595:49116|fz7445-lib     600     0       901738  901636  0,0,255
```

So, min(start) is less than max(end) only in a few cases.
I opened issue in breakdancer project.

Thank you for such a quick response!
